### ISSUE TITLE
Error in Install

### ISSUE THREAD

**Issue by tompoch2** [vdomos/domogik-plugin-vdevice#1]
sudo dmg_package -i https://github.com/vdomos/domogik-plugin-vdevice/archive/master.zip
Start downloading https://github.com/vdomos/domogik-plugin-vdevice/archive/master.zip
Error while downloading the package : SSL handshaking failed
Please try again
Retrying...
Start downloading https://github.com/vdomos/domogik-plugin-vdevice/archive/master.zip
Download finished
Upgrade a package from a zip file : /tmp/tmp3l64B7
Error while reading the json file 'None' : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.2/src/domogik/bin/package.py", line 507, in is_json_ok
    pkg_json = PackageJson(data = data)
  File "/opt/dmg/domogik-0.4.2/src/domogik/common/packagejson.py", line 145, in **init**
    raise PackageException(exp.value)
PackageException: "Error validating the json: key 'xpl_command' not found in command set_temperature"

**Comment by vdomos** [comment]
Hello,
Are you in 0.4.2 Domogik version ?

This plugin is for Domogik 0.5 (develop) version.
Strange that there is no warning on the version

**Comment by tompoch2** [comment]
Yes im use this versión

Now upgrade

Thanks

Atte.
René Gajardo Fontecha.
Ing. Computación e informática.
